Exit code: 0
Wall time: 1 seconds
Output:
import{PAGE_STATES,normalizePage,splitList,auditPage,buildBrief,jsonLd,exportHtml,escapeHtml}from'./core.js';import{seedPages}from'./data.js';
const STORE='scarlet.content-os.v2',$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let state=load(),activeId=state.pages[0]?.id||null,query='',status='すべて';
function load(){try{return JSON.parse(localStorage.getItem(STORE))||{pages:seedPages}}catch{return{pages:seedPages}}}function save(){localStorage.setItem(STORE,JSON.stringify(state))}function active(){return state.pages.find(p=>p.id===activeId)||normalizePage()}function toast(m){let e=$('#toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}function dl(name,text,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function metrics(){const audits=state.pages.map(auditPage),avg=audits.length?Math.round(audits.reduce((n,a)=>n+a.score,0)/audits.length):0;$('#avgScore').textContent=avg;const m=[['ページ',state.pages.length,'▦','登録済み'],['公開準備',state.pages.filter(p=>p.status==='公開準備').length,'↗','レビュー済み'],['根拠ソース',state.pages.reduce((n,p)=>n+p.sources.length,0),'⌁','追跡可能'],['平均品質',avg,'✓','100点満点']];$('#metrics').innerHTML=m.map(x=>`<article class="metric"><div class="top"><span>${x[0]}</span><i>${x[2]}</i></div><strong>${x[1]}</strong><small>${x[3]}</small></article>`).join('')}
function dashboard(){metrics();$('#pageList').innerHTML=state.pages.slice(0,5).map(p=>{const a=auditPage(p);return`<div class="focus-row page-row" data-open="${p.id}"><span class="quality-dot ${a.score>=75?'good':''}"></span><div><b>${escapeHtml(p.title||'無題のページ')}</b><p>${escapeHtml(p.query)} · ${p.intent}</p></div><span class="status-chip">${p.status}</span><b class="mini-score">${a.score}</b></div>`}).join('')||'<div class="empty">ページがありません</div>'}
function sourceRow(s={label:'',url:'',type:'公式資料'}){return`<div class="source-row"><select data-source="type"><option>一次情報</option><option ${s.type==='公式資料'?'selected':''}>公式資料</option><option>独自調査</option><option>専門家コメント</option><option>統計・データ</option><option>参考資料</option></select><input data-source="label" value="${escapeHtml(s.label)}" placeholder="ソース名"><input data-source="url" value="${escapeHtml(s.url)}" placeholder="https://"><button type="button" data-remove-source>×</button></div>`}
function fillEditor(p){activeId=p.id||null;const f=$('#pageForm');for(const k of['id','query','intent','audience','status','title','slug','answer','body','author','experience'])f.elements[k].value=p[k]||'';f.entities.value=p.entities.join(', ');f.internalLinks.value=p.internalLinks.join(', ');$('#sourceRows').innerHTML=(p.sources.length?p.sources:[{}]).map(sourceRow).join('');audit()}
function readEditor(){const f=$('#pageForm'),o=Object.fromEntries(new FormData(f));o.entities=splitList(o.entities);o.internalLinks=splitList(o.internalLinks);o.sources=$$('.source-row').map(r=>({type:r.querySelector('[data-source="type"]').value,label:r.querySelector('[data-source="label"]').value.trim(),url:r.querySelector('[data-source="url"]').value.trim()})).filter(s=>s.label||s.url);const old=state.pages.find(p=>p.id===o.id);return normalizePage({...old,...o,id:o.id||undefined})}
function audit(){const a=auditPage(readEditor());$('#auditScore').textContent=a.score;$('#auditChecks').innerHTML=a.checks.map(c=>`<div class="audit-check ${c.pass?'pass':''}"><span>${c.pass?'✓':'○'}</span><p>${c.label}</p><b>+${c.weight}</b></div>`).join('')}
function library(){const pages=state.pages.filter(p=>(status==='すべて'||p.status===status)&&(!query||[p.title,p.query,p.audience].join(' ').toLowerCase().includes(query)));$('#resultCount').textContent=`${pages.length}件`;$('#libraryRows').innerHTML=pages.map(p=>{const a=auditPage(p);return`<article class="content-row" data-open="${p.id}"><div><span class="intent">${p.intent}</span><h3>${escapeHtml(p.title||'無題のページ')}</h3><p>${escapeHtml(p.query)} · 更新 ${new Date(p.updatedAt).toLocaleDateString('ja-JP')}</p></div><span class="status-chip">${p.status}</span><div class="row-score"><strong>${a.score}</strong><small>QUALITY</small></div></article>`}).join('')||'<div class="empty">条件に合うページがありません</div>'}
function registry(){const all=state.pages.flatMap(p=>p.sources.map(s=>({...s,page:p.title})));$('#sourceRegistry').innerHTML=all.length?all.map(s=>`<div class="registry-row"><span class="source-type">${escapeHtml(s.type||'参考資料')}</span><div><b>${escapeHtml(s.label)}</b><a href="${escapeHtml(s.url)}" target="_blank" rel="noopener">${escapeHtml(s.url)}</a></div><small>${escapeHtml(s.page)}</small></div>`).join(''):'<div class="empty">登録ソースはありません</div>'}
function render(){dashboard();library();registry()}
function go(view){$$('.view').forEach(v=>v.classList.toggle('active',v.id===view));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===view));const t={dashboard:['コンテンツ管制塔','根拠から公開まで、引用される情報設計を一枚で。'],studio:['制作スタジオ','検索意図と根拠から、役立つページを設計します。'],library:['ページライブラリ','品質と制作状態を横断して管理します。'],sources:['根拠ソース台帳','主張の出所と利用ページを追跡します。']}[$$('#'+view)[0]?.id||view];$('#pageTitle').textContent=t[0];$('#pageSubtitle').textContent=t[1]}
document.addEventListener('click',e=>{const n=e.target.closest('[data-view]');if(n)go(n.dataset.view);const j=e.target.closest('[data-jump]');if(j)go(j.dataset.jump);const o=e.target.closest('[data-open]');if(o){activeId=o.dataset.open;fillEditor(active());go('studio')}if(e.target.matches('[data-remove-source]')){e.target.closest('.source-row').remove();audit()}});$('#newButton').onclick=()=>{activeId=null;fillEditor(normalizePage());go('studio')};$('#addSource').onclick=()=>{$('#sourceRows').insertAdjacentHTML('beforeend',sourceRow());audit()};$('#pageForm').addEventListener('input',audit);$('#pageForm').onsubmit=e=>{e.preventDefault();const p=readEditor(),i=state.pages.findIndex(x=>x.id===p.id);if(i>=0)state.pages[i]=p;else state.pages.unshift(p);activeId=p.id;save();render();fillEditor(p);toast('保存しました')};$('#briefButton').onclick=()=>{const p=readEditor();if(!p.query)return toast('主クエリを入力してください');const b=buildBrief(p);for(const k of['title','answer','body'])if(!$('#pageForm').elements[k].value)$('#pageForm').elements[k].value=b[k];audit();toast('設計案を作成しました')};$('#previewButton').onclick=()=>{const p=readEditor();$('#previewArticle').innerHTML=`<h1>${escapeHtml(p.title)}</h1><p class="lead">${escapeHtml(p.answer)}</p>`+p.body.split('\n').map(x=>x.startsWith('## ')?`<h2>${escapeHtml(x.slice(3))}</h2>`:x?`<p>${escapeHtml(x)}</p>`:'').join('')+`<div class="byline">著者: ${escapeHtml(p.author||'未設定')} · 更新: ${new Date().toLocaleDateString('ja-JP')}</div>`;$('#previewDialog').showModal()};$('#jsonldButton').onclick=()=>{$('#codeOutput').textContent=JSON.stringify(jsonLd(readEditor()),null,2);$('#codeDialog').showModal()};$('#exportHtmlButton').onclick=()=>{const p=readEditor();dl(`${p.slug||'page'}.html`,exportHtml(p),'text/html');toast('HTMLを書き出しました')};$('#search').oninput=e=>{query=e.target.value.toLowerCase();library()};$('#statusFilter').onchange=e=>{status=e.target.value;library()};$('#dataButton').onclick=()=>$('#dataDialog').showModal();$('#exportData').onclick=()=>dl('scarlet-backup.json',JSON.stringify(state,null,2),'application/json');$('#importData').onchange=async e=>{try{const x=JSON.parse(await e.target.files[0].text());if(!Array.isArray(x.pages))throw Error('pagesがありません');state={pages:x.pages.map(normalizePage)};save();activeId=state.pages[0]?.id;render();fillEditor(active());$('#dataDialog').close();toast('読み込みました')}catch(x){toast(x.message)}};$('#resetData').onclick=()=>{if(confirm('データをサンプルに戻しますか？')){state={pages:seedPages};save();activeId=state.pages[0].id;render();fillEditor(active());$('#dataDialog').close()}};fillEditor(active());render();

