
export const PAGE_STATES=["企画","執筆中","レビュー","公開準備","公開済み"];
export const INTENTS=["知りたい","比較したい","やってみたい","購入したい","行きたい"];
export function createId(prefix="page"){return `${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,7)}`}
export function normalizePage(p={}){return{id:p.id||createId(),title:String(p.title||"").trim(),slug:String(p.slug||"").trim(),query:String(p.query||"").trim(),intent:INTENTS.includes(p.intent)?p.intent:INTENTS[0],audience:String(p.audience||"").trim(),answer:String(p.answer||"").trim(),body:String(p.body||"").trim(),author:String(p.author||"").trim(),experience:String(p.experience||"").trim(),sources:Array.isArray(p.sources)?p.sources:[],entities:Array.isArray(p.entities)?p.entities:splitList(p.entities),internalLinks:Array.isArray(p.internalLinks)?p.internalLinks:splitList(p.internalLinks),schema:Array.isArray(p.schema)?p.schema:["Article"],status:PAGE_STATES.includes(p.status)?p.status:PAGE_STATES[0],updatedAt:new Date().toISOString(),createdAt:p.createdAt||new Date().toISOString()}}
export function splitList(v=""){return String(v).split(/[,、\n]/).map(x=>x.trim()).filter(Boolean)}
export function auditPage(p){const checks=[
 ["intent",!!p.query&&!!p.intent,10,"検索意図と主クエリ"],["title",p.title.length>=18&&p.title.length<=42,10,"具体的なタイトル（18〜42字）"],["answer",p.answer.length>=80&&p.answer.length<=300,12,"冒頭の直接回答（80〜300字）"],["depth",wordCount(p.body)>=350,12,"十分な本文（目安350語以上）"],["headings",(p.body.match(/^## /gm)||[]).length>=2,8,"論点別のH2見出し"],["sources",p.sources.length>=2&&p.sources.every(s=>s.url&&s.label),12,"根拠ソースを2件以上"],["primary",!!p.experience,12,"一次体験・独自データ"],["author",!!p.author,8,"著者・レビュー責任者"],["entity",p.entities.length>=2,6,"主要エンティティの明示"],["links",p.internalLinks.length>=2,5,"関連ページへの内部リンク"],["schema",p.schema.includes("Article"),5,"表示内容と一致する構造化データ"]];return{score:checks.reduce((n,c)=>n+(c[1]?c[2]:0),0),checks:checks.map(([id,pass,weight,label])=>({id,pass,weight,label}))}}
export function wordCount(v=""){return String(v).trim()?String(v).trim().split(/\s+|(?<=[。！？])/).filter(Boolean).length:0}
export function buildBrief({query,intent,audience}){return{title:`${query}をわかりやすく解説｜${audience||"読者"}向け実践ガイド`,answer:`${query}について、結論・判断基準・具体的な手順を、検証可能な根拠と実例に基づいて説明します。`,body:`## 結論\n${query}に対する端的な答えをここに記載します。\n\n## 判断基準\n読者が自分で判断できる基準を、比較表や具体的な数値とともに示します。\n\n## 実践手順\n1. 前提を確認する\n2. 選択肢を比較する\n3. 結果を検証する\n\n## 注意点\n例外、制約、向かないケースを明記します。\n\n## よくある質問\n読者が次に尋ねる質問へ簡潔に回答します。`,intent}}
export function jsonLd(p,base="https://example.com"){return{"@context":"https://schema.org","@type":"Article",headline:p.title,description:p.answer,author:{"@type":"Person",name:p.author||"編集部"},datePublished:p.createdAt,dateModified:p.updatedAt,mainEntityOfPage:`${base.replace(/\/$/,"")}/${p.slug}`,about:p.entities.map(name=>({"@type":"Thing",name}))}}
export function exportHtml(p){const sections=p.body.split('\n').map(line=>line.startsWith('## ')?`<h2>${escapeHtml(line.slice(3))}</h2>`:line.startsWith('# ')?`<h1>${escapeHtml(line.slice(2))}</h1>`:line?`<p>${escapeHtml(line)}</p>`:'').join('\n');return `<!doctype html>\n<html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(p.title)}</title><meta name="description" content="${escapeHtml(p.answer)}"><script type="application/ld+json">${JSON.stringify(jsonLd(p))}<\/script></head><body><main><article><header><h1>${escapeHtml(p.title)}</h1><p>${escapeHtml(p.answer)}</p></header>${sections}<footer><p>著者: ${escapeHtml(p.author||'編集部')}</p></footer></article></main></body></html>`}
export function escapeHtml(v=""){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}

